import Head from "next/head";
import React, { useState } from "react";
import Image from "next/legacy/image";

import me from "../../public/me.png";
import {
  AiFillLinkedin,
  AiFillMail,
  AiFillGithub,
} from "react-icons/ai";
import { MdLightbulb } from "react-icons/md";

import web1 from "../../public/web1.png";
import web2 from "../../public/web2.png";
import web3 from "../../public/web3.jpg";
import web4 from "../../public/web4.png";
import web5 from "../../public/web5.png";

import design from "../../public/design.png";



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);



  return (
    <>
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Matheus | My Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
          <section className="min-h-screen">
            <nav className="py-10 mb-12 flex justify-between dark:text-white">
              <h1 className="font-SerifBLD text-xl">my portfolio</h1>
              <ul className="flex items-center">
                <li>
                  <MdLightbulb
                    onClick={() => setDarkMode(!darkMode)}
                    className=" cursor-pointer text-2xl ml-6"
                  />
                </li>
                <li>
                  <a
                    className="bg-gradient-to-r from-yellow-500 text- to-amber-500 text-white px-4 py-2 border-none rounded-md ml-8 font-medium"
                    href="#"
                  >
                    Donwload Resume
                  </a>
                </li>
              </ul>
            </nav>

            <div className="text-center p-10 py-10">
              <p className="text-lg text-yellow-600  dark:text-yellow-500 md:text-lg font-SerifBLD">Let me introduce myself, </p>
              <h2 className="text-5xl py-2 text-amber-600   dark:text-amber-400 md:text-6xl font-SerifBLD">
                I&apos;m Matheus Pereira
              </h2>
              <h3 className="text-xl py-2 font-mono dark:text-white md:text-3xl">
                Piauí, Brazil
              </h3>
              <p className="text-md py-4 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
                Developer passionate about simple solutions to difficult problems.
              </p>
              <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400 ">
                <AiFillGithub className="cursor-pointer transition ease-in-out delay-150  hover:-translate-y-1 hover:text-black dark:hover:text-white hover:scale-110  duration-300" href="https://github.com/matheudsp" />
                <AiFillLinkedin className="cursor-pointer transition ease-in-out delay-150  hover:-translate-y-1 hover:text-blue-600 hover:scale-110  duration-300" href="https://www.linkedin.com/in/matheus-pereira-3a057a224/" />
                <AiFillMail className="cursor-pointer transition ease-in-out delay-150  hover:-translate-y-1 hover:text-red-600 hover:scale-110  duration-300" href="" />

              </div>
                <div className="mx-auto bg-gradient-to-b from-amber-500 rounded-full w-80 h-80 relative overflow-hidden mt-10 md:h-96 md:w-96">
                <Image src={me} layout="fill" objectFit="cover" />
              </div>
            </div>
          </section>
          <section >
            <div>
              <h3 className="text-3xl py-1 dark:text-white font-SerifBLD">Skills</h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                Since the beginning of my journey as a IT student and developer, I made some projects using tools that aroused curiosity. And during that process, I learned these tools.
              </p>

            </div>
            <div className="lg:flex gap-10">
              <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-slate-700 flex-1">
                <Image src={design} width={100} height={100} />
                <h3 className="text-base pt-8 pb-2 font-SerifBLD dark:text-white uppercase -tracking-tighter">
                  Technologies
                </h3>

                <h4 className="py-4 text-amber-600 dark:text-amber-400 font-medium">Tools I already used</h4>
                <p className="text-zinc-400 py-1 text-sm dark:text-zinc-200 font-SerifBLD">🔴HTML5,CSS3 & Bootstrap</p>
                <p className="text-zinc-400 py-1 dark:text-zinc-200 font-SerifBLD ">🔴React</p>
                <p className="text-zinc-400 py-1 dark:text-zinc-200 font-SerifBLD">🔴Javascript</p>
                <p className="text-zinc-400 py-1 dark:text-zinc-200 font-SerifBLD">🔴Python</p>
              </div>
              

            </div>
          </section>
          <section className="py-10">
            <div>
              <h3 className="text-3xl py-1 dark:text-white font-SerifBLD">Projects</h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                And here are some projects I&apos;ve developed.
              </p>

            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1 ">
                <Image
                  className="rounded-lg object-cover p-10 transition-opacity hover:opacity-60  "
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  src={web1}
                  alt="image of a project 1"
                  href="https://github.com/matheudsp/campainha-alerta.git"
                />
              </div>
              <div className="basis-1/3 flex-1 mt-5  ">
                <Image
                  className="rounded-lg object-cover transition-opacity hover:opacity-60 "
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  alt="image of a project 2"
                  src={web2}
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover transition-opacity hover:opacity-60 "
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  alt="image of a project 3"
                  src={web3}
                />
              </div>
              <div className="basis-1/3 flex-1 mt-5">
                <Image
                  className="rounded-lg object-cover transition-opacity hover:opacity-60 "
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  alt="image of a project 4"
                  src={web4}
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  className="rounded-lg object-cover transition-opacity hover:opacity-60 "
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  alt="image of a project 5"
                  src={web5}
                />
              </div>
              <div className="basis-1/3 flex-1 mt-5">
                <h2 className="text-center text-9xl dark:text-white">...</h2>
              </div>
            </div>
          </section>
        </main>
      </div>
    </>

  );
}

